// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// SetAvatarSucceededResponse - User with updated avatar.
type SetAvatarSucceededResponse struct {
	Response User `json:"response"`
}

// AssertSetAvatarSucceededResponseRequired checks if the required fields are not zero-ed
func AssertSetAvatarSucceededResponseRequired(obj SetAvatarSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUserRequired(obj.Response); err != nil {
		return err
	}
	return nil
}

// AssertSetAvatarSucceededResponseConstraints checks if the values respects the defined constraints
func AssertSetAvatarSucceededResponseConstraints(obj SetAvatarSucceededResponse) error {
	if err := AssertUserConstraints(obj.Response); err != nil {
		return err
	}
	return nil
}
