// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// CreateSpendingsGroupRequest - Signup Request
type CreateSpendingsGroupRequest struct {
	Payload SpendingsGroupPayload `json:"payload"`
}

// AssertCreateSpendingsGroupRequestRequired checks if the required fields are not zero-ed
func AssertCreateSpendingsGroupRequestRequired(obj CreateSpendingsGroupRequest) error {
	elements := map[string]interface{}{
		"payload": obj.Payload,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSpendingsGroupPayloadRequired(obj.Payload); err != nil {
		return err
	}
	return nil
}

// AssertCreateSpendingsGroupRequestConstraints checks if the values respects the defined constraints
func AssertCreateSpendingsGroupRequestConstraints(obj CreateSpendingsGroupRequest) error {
	if err := AssertSpendingsGroupPayloadConstraints(obj.Payload); err != nil {
		return err
	}
	return nil
}
