// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type GetProfileSucceededResponse struct {
	Response Profile `json:"response"`
}

// AssertGetProfileSucceededResponseRequired checks if the required fields are not zero-ed
func AssertGetProfileSucceededResponseRequired(obj GetProfileSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertProfileRequired(obj.Response); err != nil {
		return err
	}
	return nil
}

// AssertGetProfileSucceededResponseConstraints checks if the values respects the defined constraints
func AssertGetProfileSucceededResponseConstraints(obj GetProfileSucceededResponse) error {
	if err := AssertProfileConstraints(obj.Response); err != nil {
		return err
	}
	return nil
}
