// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type SpendingsGroupParticipant struct {

	// Participant's identifier.
	UserId string `json:"userId"`

	Status SpendingsGroupParticipantStatus `json:"status"`
}

// AssertSpendingsGroupParticipantRequired checks if the required fields are not zero-ed
func AssertSpendingsGroupParticipantRequired(obj SpendingsGroupParticipant) error {
	elements := map[string]interface{}{
		"userId": obj.UserId,
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSpendingsGroupParticipantConstraints checks if the values respects the defined constraints
func AssertSpendingsGroupParticipantConstraints(obj SpendingsGroupParticipant) error {
	return nil
}
