// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type GetSpendingGroupsSucceededResponse struct {
	Response []SpendingsGroup `json:"response"`
}

// AssertGetSpendingGroupsSucceededResponseRequired checks if the required fields are not zero-ed
func AssertGetSpendingGroupsSucceededResponseRequired(obj GetSpendingGroupsSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Response {
		if err := AssertSpendingsGroupRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetSpendingGroupsSucceededResponseConstraints checks if the values respects the defined constraints
func AssertGetSpendingGroupsSucceededResponseConstraints(obj GetSpendingGroupsSucceededResponse) error {
	for _, el := range obj.Response {
		if err := AssertSpendingsGroupConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
