// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type SetAvatarRequest struct {
	DataBase64 string `json:"dataBase64"`

	UserId *string `json:"userId,omitempty"`
}

// AssertSetAvatarRequestRequired checks if the required fields are not zero-ed
func AssertSetAvatarRequestRequired(obj SetAvatarRequest) error {
	elements := map[string]interface{}{
		"dataBase64": obj.DataBase64,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSetAvatarRequestConstraints checks if the values respects the defined constraints
func AssertSetAvatarRequestConstraints(obj SetAvatarRequest) error {
	return nil
}
