// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type SpendingShare struct {

	// User Identifier.
	UserId string `json:"userId"`

	// Participant's owed amount of money.
	Amount int64 `json:"amount"`
}

// AssertSpendingShareRequired checks if the required fields are not zero-ed
func AssertSpendingShareRequired(obj SpendingShare) error {
	elements := map[string]interface{}{
		"userId": obj.UserId,
		"amount": obj.Amount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSpendingShareConstraints checks if the values respects the defined constraints
func AssertSpendingShareConstraints(obj SpendingShare) error {
	return nil
}
