// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type PushOperationsRequest struct {
	DeviceId string `json:"deviceId,omitempty"`

	Operations []Operation `json:"operations,omitempty"`
}

// AssertPushOperationsRequestRequired checks if the required fields are not zero-ed
func AssertPushOperationsRequestRequired(obj PushOperationsRequest) error {
	for _, el := range obj.Operations {
		if err := AssertOperationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPushOperationsRequestConstraints checks if the values respects the defined constraints
func AssertPushOperationsRequestConstraints(obj PushOperationsRequest) error {
	for _, el := range obj.Operations {
		if err := AssertOperationConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
