// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

import (
	"fmt"
)

type SpendingsGroupParticipantStatus string

// List of SpendingsGroupParticipantStatus
const (
	INVITED  SpendingsGroupParticipantStatus = "invited"
	MEMBER   SpendingsGroupParticipantStatus = "member"
	DECLINED SpendingsGroupParticipantStatus = "declined"
)

// AllowedSpendingsGroupParticipantStatusEnumValues is all the allowed values of SpendingsGroupParticipantStatus enum
var AllowedSpendingsGroupParticipantStatusEnumValues = []SpendingsGroupParticipantStatus{
	"invited",
	"member",
	"declined",
}

// validSpendingsGroupParticipantStatusEnumValue provides a map of SpendingsGroupParticipantStatuss for fast verification of use input
var validSpendingsGroupParticipantStatusEnumValues = map[SpendingsGroupParticipantStatus]struct{}{
	"invited":  {},
	"member":   {},
	"declined": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SpendingsGroupParticipantStatus) IsValid() bool {
	_, ok := validSpendingsGroupParticipantStatusEnumValues[v]
	return ok
}

// NewSpendingsGroupParticipantStatusFromValue returns a pointer to a valid SpendingsGroupParticipantStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSpendingsGroupParticipantStatusFromValue(v string) (SpendingsGroupParticipantStatus, error) {
	ev := SpendingsGroupParticipantStatus(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for SpendingsGroupParticipantStatus: valid values are %v", v, AllowedSpendingsGroupParticipantStatusEnumValues)
}

// AssertSpendingsGroupParticipantStatusRequired checks if the required fields are not zero-ed
func AssertSpendingsGroupParticipantStatusRequired(obj SpendingsGroupParticipantStatus) error {
	return nil
}

// AssertSpendingsGroupParticipantStatusConstraints checks if the values respects the defined constraints
func AssertSpendingsGroupParticipantStatusConstraints(obj SpendingsGroupParticipantStatus) error {
	return nil
}
