// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type Spending struct {

	// Spending's identifier.
	Id string `json:"id"`

	Payload SpendingPayload `json:"payload"`
}

// AssertSpendingRequired checks if the required fields are not zero-ed
func AssertSpendingRequired(obj Spending) error {
	elements := map[string]interface{}{
		"id":      obj.Id,
		"payload": obj.Payload,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSpendingPayloadRequired(obj.Payload); err != nil {
		return err
	}
	return nil
}

// AssertSpendingConstraints checks if the values respects the defined constraints
func AssertSpendingConstraints(obj Spending) error {
	if err := AssertSpendingPayloadConstraints(obj.Payload); err != nil {
		return err
	}
	return nil
}
