// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type SpendingsGroupPayload struct {

	// Spending group's display name.
	Name *string `json:"name,omitempty"`

	UserIds []string `json:"userIds"`

	// Spending's group creation unix timestamp.
	CreatedAt int32 `json:"createdAt,omitempty"`

	Spendings []SpendingPayload `json:"spendings"`
}

// AssertSpendingsGroupPayloadRequired checks if the required fields are not zero-ed
func AssertSpendingsGroupPayloadRequired(obj SpendingsGroupPayload) error {
	elements := map[string]interface{}{
		"userIds":   obj.UserIds,
		"spendings": obj.Spendings,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Spendings {
		if err := AssertSpendingPayloadRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSpendingsGroupPayloadConstraints checks if the values respects the defined constraints
func AssertSpendingsGroupPayloadConstraints(obj SpendingsGroupPayload) error {
	for _, el := range obj.Spendings {
		if err := AssertSpendingPayloadConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
