// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// Credentials - User Credentials.
type Credentials struct {

	// User email.
	Email string `json:"email"`

	// User password.
	Password string `json:"password"`
}

// AssertCredentialsRequired checks if the required fields are not zero-ed
func AssertCredentialsRequired(obj Credentials) error {
	elements := map[string]interface{}{
		"email":    obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCredentialsConstraints checks if the values respects the defined constraints
func AssertCredentialsConstraints(obj Credentials) error {
	return nil
}
