// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type PushOperationsSucceededResponse struct {
	Response []SomeOperation `json:"response"`
}

// AssertPushOperationsSucceededResponseRequired checks if the required fields are not zero-ed
func AssertPushOperationsSucceededResponseRequired(obj PushOperationsSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Response {
		if err := AssertSomeOperationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPushOperationsSucceededResponseConstraints checks if the values respects the defined constraints
func AssertPushOperationsSucceededResponseConstraints(obj PushOperationsSucceededResponse) error {
	for _, el := range obj.Response {
		if err := AssertSomeOperationConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
