// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type AddSpendingSucceededResponse struct {
	Response Spending `json:"response"`
}

// AssertAddSpendingSucceededResponseRequired checks if the required fields are not zero-ed
func AssertAddSpendingSucceededResponseRequired(obj AddSpendingSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSpendingRequired(obj.Response); err != nil {
		return err
	}
	return nil
}

// AssertAddSpendingSucceededResponseConstraints checks if the values respects the defined constraints
func AssertAddSpendingSucceededResponseConstraints(obj AddSpendingSucceededResponse) error {
	if err := AssertSpendingConstraints(obj.Response); err != nil {
		return err
	}
	return nil
}
