// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type UploadImageOperation struct {
	UploadImage UploadImageOperationUploadImage `json:"uploadImage"`
}

// AssertUploadImageOperationRequired checks if the required fields are not zero-ed
func AssertUploadImageOperationRequired(obj UploadImageOperation) error {
	elements := map[string]interface{}{
		"uploadImage": obj.UploadImage,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUploadImageOperationUploadImageRequired(obj.UploadImage); err != nil {
		return err
	}
	return nil
}

// AssertUploadImageOperationConstraints checks if the values respects the defined constraints
func AssertUploadImageOperationConstraints(obj UploadImageOperation) error {
	if err := AssertUploadImageOperationUploadImageConstraints(obj.UploadImage); err != nil {
		return err
	}
	return nil
}
