// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type CreateSpendingPushPayload struct {
	Cs CreateSpendingPushPayloadCs `json:"cs"`
}

// AssertCreateSpendingPushPayloadRequired checks if the required fields are not zero-ed
func AssertCreateSpendingPushPayloadRequired(obj CreateSpendingPushPayload) error {
	elements := map[string]interface{}{
		"cs": obj.Cs,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCreateSpendingPushPayloadCsRequired(obj.Cs); err != nil {
		return err
	}
	return nil
}

// AssertCreateSpendingPushPayloadConstraints checks if the values respects the defined constraints
func AssertCreateSpendingPushPayloadConstraints(obj CreateSpendingPushPayload) error {
	if err := AssertCreateSpendingPushPayloadCsConstraints(obj.Cs); err != nil {
		return err
	}
	return nil
}
