// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// CreateSpendingOperationCreateSpending - Create spending operation
type CreateSpendingOperationCreateSpending struct {
	SpendingId string `json:"spendingId"`

	GroupId string `json:"groupId"`

	// Spending display name.
	Name string `json:"name"`

	// Spending's currency 3-letter code. (ISO 4217)
	Currency string `json:"currency"`

	// Spending's total amount multiplied by 100 (123 amount for currency code USD means $1.23)
	Amount int64 `json:"amount"`

	Shares []SpendingShare `json:"shares"`
}

// AssertCreateSpendingOperationCreateSpendingRequired checks if the required fields are not zero-ed
func AssertCreateSpendingOperationCreateSpendingRequired(obj CreateSpendingOperationCreateSpending) error {
	elements := map[string]interface{}{
		"spendingId": obj.SpendingId,
		"groupId":    obj.GroupId,
		"name":       obj.Name,
		"currency":   obj.Currency,
		"amount":     obj.Amount,
		"shares":     obj.Shares,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Shares {
		if err := AssertSpendingShareRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCreateSpendingOperationCreateSpendingConstraints checks if the values respects the defined constraints
func AssertCreateSpendingOperationCreateSpendingConstraints(obj CreateSpendingOperationCreateSpending) error {
	for _, el := range obj.Shares {
		if err := AssertSpendingShareConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
