// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// CreateUserRequest - Signup Request
type CreateUserRequest struct {
	User UserPayload `json:"user"`
}

// AssertCreateUserRequestRequired checks if the required fields are not zero-ed
func AssertCreateUserRequestRequired(obj CreateUserRequest) error {
	elements := map[string]interface{}{
		"user": obj.User,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUserPayloadRequired(obj.User); err != nil {
		return err
	}
	return nil
}

// AssertCreateUserRequestConstraints checks if the values respects the defined constraints
func AssertCreateUserRequestConstraints(obj CreateUserRequest) error {
	if err := AssertUserPayloadConstraints(obj.User); err != nil {
		return err
	}
	return nil
}
