// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type CreateSpendingsGroupSucceededResponse struct {
	Response SpendingsGroup `json:"response"`
}

// AssertCreateSpendingsGroupSucceededResponseRequired checks if the required fields are not zero-ed
func AssertCreateSpendingsGroupSucceededResponseRequired(obj CreateSpendingsGroupSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSpendingsGroupRequired(obj.Response); err != nil {
		return err
	}
	return nil
}

// AssertCreateSpendingsGroupSucceededResponseConstraints checks if the values respects the defined constraints
func AssertCreateSpendingsGroupSucceededResponseConstraints(obj CreateSpendingsGroupSucceededResponse) error {
	if err := AssertSpendingsGroupConstraints(obj.Response); err != nil {
		return err
	}
	return nil
}
