// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type UpdatePasswordRequest struct {
	Old string `json:"old"`

	New string `json:"new"`
}

// AssertUpdatePasswordRequestRequired checks if the required fields are not zero-ed
func AssertUpdatePasswordRequestRequired(obj UpdatePasswordRequest) error {
	elements := map[string]interface{}{
		"old": obj.Old,
		"new": obj.New,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUpdatePasswordRequestConstraints checks if the values respects the defined constraints
func AssertUpdatePasswordRequestConstraints(obj UpdatePasswordRequest) error {
	return nil
}
