// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type RegisterForPushNotificationsRequest struct {
	Token string `json:"token"`
}

// AssertRegisterForPushNotificationsRequestRequired checks if the required fields are not zero-ed
func AssertRegisterForPushNotificationsRequestRequired(obj RegisterForPushNotificationsRequest) error {
	elements := map[string]interface{}{
		"token": obj.Token,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRegisterForPushNotificationsRequestConstraints checks if the values respects the defined constraints
func AssertRegisterForPushNotificationsRequestConstraints(obj RegisterForPushNotificationsRequest) error {
	return nil
}
