// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




// Image - Image.
type Image struct {

	// Image identifier.
	Id string `json:"id"`

	// base64 string representation of the image.
	Base64 string `json:"base64"`
}

// AssertImageRequired checks if the required fields are not zero-ed
func AssertImageRequired(obj Image) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"base64": obj.Base64,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertImageConstraints checks if the values respects the defined constraints
func AssertImageConstraints(obj Image) error {
	return nil
}
