// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




type VerifyEmailOperationVerifyEmail struct {

	Verified bool `json:"verified"`
}

// AssertVerifyEmailOperationVerifyEmailRequired checks if the required fields are not zero-ed
func AssertVerifyEmailOperationVerifyEmailRequired(obj VerifyEmailOperationVerifyEmail) error {
	elements := map[string]interface{}{
		"verified": obj.Verified,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertVerifyEmailOperationVerifyEmailConstraints checks if the values respects the defined constraints
func AssertVerifyEmailOperationVerifyEmailConstraints(obj VerifyEmailOperationVerifyEmail) error {
	return nil
}
