// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// Session - User Session.
type Session struct {

	// User Identifier.
	Id string `json:"id"`

	// Users access token.
	AccessToken string `json:"accessToken"`

	// Users refresh token.
	RefreshToken string `json:"refreshToken"`
}

// AssertSessionRequired checks if the required fields are not zero-ed
func AssertSessionRequired(obj Session) error {
	elements := map[string]interface{}{
		"id":           obj.Id,
		"accessToken":  obj.AccessToken,
		"refreshToken": obj.RefreshToken,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSessionConstraints checks if the values respects the defined constraints
func AssertSessionConstraints(obj Session) error {
	return nil
}
