// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// AcceptSpendingGroupInviteRequest - Signup Request
type AcceptSpendingGroupInviteRequest struct {
	GroupId string `json:"groupId"`
}

// AssertAcceptSpendingGroupInviteRequestRequired checks if the required fields are not zero-ed
func AssertAcceptSpendingGroupInviteRequestRequired(obj AcceptSpendingGroupInviteRequest) error {
	elements := map[string]interface{}{
		"groupId": obj.GroupId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAcceptSpendingGroupInviteRequestConstraints checks if the values respects the defined constraints
func AssertAcceptSpendingGroupInviteRequestConstraints(obj AcceptSpendingGroupInviteRequest) error {
	return nil
}
