// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type CreateUserOperation struct {
	CreateUser CreateUserOperationCreateUser `json:"createUser"`
}

// AssertCreateUserOperationRequired checks if the required fields are not zero-ed
func AssertCreateUserOperationRequired(obj CreateUserOperation) error {
	elements := map[string]interface{}{
		"createUser": obj.CreateUser,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCreateUserOperationCreateUserRequired(obj.CreateUser); err != nil {
		return err
	}
	return nil
}

// AssertCreateUserOperationConstraints checks if the values respects the defined constraints
func AssertCreateUserOperationConstraints(obj CreateUserOperation) error {
	if err := AssertCreateUserOperationCreateUserConstraints(obj.CreateUser); err != nil {
		return err
	}
	return nil
}
