// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




// DeleteSpendingGroupOperation - Delete spending group operation
type DeleteSpendingGroupOperation struct {

	DeleteSpendingGroup DeleteSpendingGroupOperationDeleteSpendingGroup `json:"deleteSpendingGroup"`
}

// AssertDeleteSpendingGroupOperationRequired checks if the required fields are not zero-ed
func AssertDeleteSpendingGroupOperationRequired(obj DeleteSpendingGroupOperation) error {
	elements := map[string]interface{}{
		"deleteSpendingGroup": obj.DeleteSpendingGroup,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertDeleteSpendingGroupOperationDeleteSpendingGroupRequired(obj.DeleteSpendingGroup); err != nil {
		return err
	}
	return nil
}

// AssertDeleteSpendingGroupOperationConstraints checks if the values respects the defined constraints
func AssertDeleteSpendingGroupOperationConstraints(obj DeleteSpendingGroupOperation) error {
	if err := AssertDeleteSpendingGroupOperationDeleteSpendingGroupConstraints(obj.DeleteSpendingGroup); err != nil {
		return err
	}
	return nil
}
