// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




type DeleteSpendingGroupOperationDeleteSpendingGroup struct {

	GroupId string `json:"groupId"`
}

// AssertDeleteSpendingGroupOperationDeleteSpendingGroupRequired checks if the required fields are not zero-ed
func AssertDeleteSpendingGroupOperationDeleteSpendingGroupRequired(obj DeleteSpendingGroupOperationDeleteSpendingGroup) error {
	elements := map[string]interface{}{
		"groupId": obj.GroupId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDeleteSpendingGroupOperationDeleteSpendingGroupConstraints checks if the values respects the defined constraints
func AssertDeleteSpendingGroupOperationDeleteSpendingGroupConstraints(obj DeleteSpendingGroupOperationDeleteSpendingGroup) error {
	return nil
}
