// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// UserPayload - Users payload.
type UserPayload struct {

	// Display name.
	DisplayName string `json:"displayName"`

	// Avatar data.
	AvatarBase64Data *string `json:"avatarBase64Data,omitempty"`
}

// AssertUserPayloadRequired checks if the required fields are not zero-ed
func AssertUserPayloadRequired(obj UserPayload) error {
	elements := map[string]interface{}{
		"displayName": obj.DisplayName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserPayloadConstraints checks if the values respects the defined constraints
func AssertUserPayloadConstraints(obj UserPayload) error {
	return nil
}
