// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// DeleteSpendingOperation - Delete spending operation
type DeleteSpendingOperation struct {
	DeleteSpending DeleteSpendingOperationDeleteSpending `json:"deleteSpending"`
}

// AssertDeleteSpendingOperationRequired checks if the required fields are not zero-ed
func AssertDeleteSpendingOperationRequired(obj DeleteSpendingOperation) error {
	elements := map[string]interface{}{
		"deleteSpending": obj.DeleteSpending,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertDeleteSpendingOperationDeleteSpendingRequired(obj.DeleteSpending); err != nil {
		return err
	}
	return nil
}

// AssertDeleteSpendingOperationConstraints checks if the values respects the defined constraints
func AssertDeleteSpendingOperationConstraints(obj DeleteSpendingOperation) error {
	if err := AssertDeleteSpendingOperationDeleteSpendingConstraints(obj.DeleteSpending); err != nil {
		return err
	}
	return nil
}
