// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




type PullOperationsSucceededResponse struct {

	Response []Operation `json:"response"`
}

// AssertPullOperationsSucceededResponseRequired checks if the required fields are not zero-ed
func AssertPullOperationsSucceededResponseRequired(obj PullOperationsSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Response {
		if err := AssertOperationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPullOperationsSucceededResponseConstraints checks if the values respects the defined constraints
func AssertPullOperationsSucceededResponseConstraints(obj PullOperationsSucceededResponse) error {
	for _, el := range obj.Response {
		if err := AssertOperationConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
