// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type CreateSpendingGroupOperationCreateSpendingGroup struct {
	GroupId string `json:"groupId"`

	Participants []string `json:"participants"`

	DisplayName *string `json:"displayName,omitempty"`
}

// AssertCreateSpendingGroupOperationCreateSpendingGroupRequired checks if the required fields are not zero-ed
func AssertCreateSpendingGroupOperationCreateSpendingGroupRequired(obj CreateSpendingGroupOperationCreateSpendingGroup) error {
	elements := map[string]interface{}{
		"groupId":      obj.GroupId,
		"participants": obj.Participants,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateSpendingGroupOperationCreateSpendingGroupConstraints checks if the values respects the defined constraints
func AssertCreateSpendingGroupOperationCreateSpendingGroupConstraints(obj CreateSpendingGroupOperationCreateSpendingGroup) error {
	return nil
}
