// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




// StartupData - All data required to startup a user session
type StartupData struct {

	Session Session `json:"session"`

	Operations []Operation `json:"operations"`
}

// AssertStartupDataRequired checks if the required fields are not zero-ed
func AssertStartupDataRequired(obj StartupData) error {
	elements := map[string]interface{}{
		"session": obj.Session,
		"operations": obj.Operations,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSessionRequired(obj.Session); err != nil {
		return err
	}
	for _, el := range obj.Operations {
		if err := AssertOperationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertStartupDataConstraints checks if the values respects the defined constraints
func AssertStartupDataConstraints(obj StartupData) error {
	if err := AssertSessionConstraints(obj.Session); err != nil {
		return err
	}
	for _, el := range obj.Operations {
		if err := AssertOperationConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
