// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type UpdateAvatarOperation struct {
	UpdateAvatar UpdateAvatarOperationUpdateAvatar `json:"updateAvatar"`
}

// AssertUpdateAvatarOperationRequired checks if the required fields are not zero-ed
func AssertUpdateAvatarOperationRequired(obj UpdateAvatarOperation) error {
	elements := map[string]interface{}{
		"updateAvatar": obj.UpdateAvatar,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUpdateAvatarOperationUpdateAvatarRequired(obj.UpdateAvatar); err != nil {
		return err
	}
	return nil
}

// AssertUpdateAvatarOperationConstraints checks if the values respects the defined constraints
func AssertUpdateAvatarOperationConstraints(obj UpdateAvatarOperation) error {
	if err := AssertUpdateAvatarOperationUpdateAvatarConstraints(obj.UpdateAvatar); err != nil {
		return err
	}
	return nil
}
