// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type SignupSucceededResponse struct {
	Response StartupData `json:"response"`
}

// AssertSignupSucceededResponseRequired checks if the required fields are not zero-ed
func AssertSignupSucceededResponseRequired(obj SignupSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertStartupDataRequired(obj.Response); err != nil {
		return err
	}
	return nil
}

// AssertSignupSucceededResponseConstraints checks if the values respects the defined constraints
func AssertSignupSucceededResponseConstraints(obj SignupSucceededResponse) error {
	if err := AssertStartupDataConstraints(obj.Response); err != nil {
		return err
	}
	return nil
}
