// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// SetDisplayNameRequest - User with updated display name.
type SetDisplayNameRequest struct {
	UserId *string `json:"userId,omitempty"`

	DisplayName string `json:"displayName"`
}

// AssertSetDisplayNameRequestRequired checks if the required fields are not zero-ed
func AssertSetDisplayNameRequestRequired(obj SetDisplayNameRequest) error {
	elements := map[string]interface{}{
		"displayName": obj.DisplayName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSetDisplayNameRequestConstraints checks if the values respects the defined constraints
func AssertSetDisplayNameRequestConstraints(obj SetDisplayNameRequest) error {
	return nil
}
