// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




type ConfirmEmailRequest struct {

	Code string `json:"code"`
}

// AssertConfirmEmailRequestRequired checks if the required fields are not zero-ed
func AssertConfirmEmailRequestRequired(obj ConfirmEmailRequest) error {
	elements := map[string]interface{}{
		"code": obj.Code,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertConfirmEmailRequestConstraints checks if the values respects the defined constraints
func AssertConfirmEmailRequestConstraints(obj ConfirmEmailRequest) error {
	return nil
}
