// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// Profile - User Profile.
type Profile struct {
	User User `json:"user,omitempty"`

	// Users email.
	Email string `json:"email,omitempty"`

	// Is users email verified.
	EmailVerified bool `json:"emailVerified,omitempty"`
}

// AssertProfileRequired checks if the required fields are not zero-ed
func AssertProfileRequired(obj Profile) error {
	if err := AssertUserRequired(obj.User); err != nil {
		return err
	}
	return nil
}

// AssertProfileConstraints checks if the values respects the defined constraints
func AssertProfileConstraints(obj Profile) error {
	if err := AssertUserConstraints(obj.User); err != nil {
		return err
	}
	return nil
}
