// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// CreateUserOperationCreateUser - Create user operation
type CreateUserOperationCreateUser struct {
	UserId string `json:"userId"`

	DisplayName string `json:"displayName"`
}

// AssertCreateUserOperationCreateUserRequired checks if the required fields are not zero-ed
func AssertCreateUserOperationCreateUserRequired(obj CreateUserOperationCreateUser) error {
	elements := map[string]interface{}{
		"userId":      obj.UserId,
		"displayName": obj.DisplayName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateUserOperationCreateUserConstraints checks if the values respects the defined constraints
func AssertCreateUserOperationCreateUserConstraints(obj CreateUserOperationCreateUser) error {
	return nil
}
