// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




type UpdateAvatarOperationUpdateAvatar struct {

	UserId string `json:"userId"`

	ImageId string `json:"imageId"`
}

// AssertUpdateAvatarOperationUpdateAvatarRequired checks if the required fields are not zero-ed
func AssertUpdateAvatarOperationUpdateAvatarRequired(obj UpdateAvatarOperationUpdateAvatar) error {
	elements := map[string]interface{}{
		"userId": obj.UserId,
		"imageId": obj.ImageId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUpdateAvatarOperationUpdateAvatarConstraints checks if the values respects the defined constraints
func AssertUpdateAvatarOperationUpdateAvatarConstraints(obj UpdateAvatarOperationUpdateAvatar) error {
	return nil
}
