// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type GetAvatarsSucceededResponse struct {
	Response map[string]Image `json:"response"`
}

// AssertGetAvatarsSucceededResponseRequired checks if the required fields are not zero-ed
func AssertGetAvatarsSucceededResponseRequired(obj GetAvatarsSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGetAvatarsSucceededResponseConstraints checks if the values respects the defined constraints
func AssertGetAvatarsSucceededResponseConstraints(obj GetAvatarsSucceededResponse) error {
	return nil
}
