// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type GetUsersSucceededResponse struct {
	Response []User `json:"response"`
}

// AssertGetUsersSucceededResponseRequired checks if the required fields are not zero-ed
func AssertGetUsersSucceededResponseRequired(obj GetUsersSucceededResponse) error {
	elements := map[string]interface{}{
		"response": obj.Response,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Response {
		if err := AssertUserRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetUsersSucceededResponseConstraints checks if the values respects the defined constraints
func AssertGetUsersSucceededResponseConstraints(obj GetUsersSucceededResponse) error {
	for _, el := range obj.Response {
		if err := AssertUserConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
