// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




// BindUserOperation - Bind user operation
type BindUserOperation struct {

	BindUser BindUserOperationBindUser `json:"bindUser"`
}

// AssertBindUserOperationRequired checks if the required fields are not zero-ed
func AssertBindUserOperationRequired(obj BindUserOperation) error {
	elements := map[string]interface{}{
		"bindUser": obj.BindUser,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertBindUserOperationBindUserRequired(obj.BindUser); err != nil {
		return err
	}
	return nil
}

// AssertBindUserOperationConstraints checks if the values respects the defined constraints
func AssertBindUserOperationConstraints(obj BindUserOperation) error {
	if err := AssertBindUserOperationBindUserConstraints(obj.BindUser); err != nil {
		return err
	}
	return nil
}
