// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type CreateSpendingGroupPushPayload struct {
	Csg CreateSpendingGroupPushPayloadCsg `json:"csg"`
}

// AssertCreateSpendingGroupPushPayloadRequired checks if the required fields are not zero-ed
func AssertCreateSpendingGroupPushPayloadRequired(obj CreateSpendingGroupPushPayload) error {
	elements := map[string]interface{}{
		"csg": obj.Csg,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCreateSpendingGroupPushPayloadCsgRequired(obj.Csg); err != nil {
		return err
	}
	return nil
}

// AssertCreateSpendingGroupPushPayloadConstraints checks if the values respects the defined constraints
func AssertCreateSpendingGroupPushPayloadConstraints(obj CreateSpendingGroupPushPayload) error {
	if err := AssertCreateSpendingGroupPushPayloadCsgConstraints(obj.Csg); err != nil {
		return err
	}
	return nil
}
