// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




type DeleteSpendingOperationDeleteSpending struct {

	SpendingId string `json:"spendingId"`

	GroupId string `json:"groupId"`
}

// AssertDeleteSpendingOperationDeleteSpendingRequired checks if the required fields are not zero-ed
func AssertDeleteSpendingOperationDeleteSpendingRequired(obj DeleteSpendingOperationDeleteSpending) error {
	elements := map[string]interface{}{
		"spendingId": obj.SpendingId,
		"groupId": obj.GroupId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDeleteSpendingOperationDeleteSpendingConstraints checks if the values respects the defined constraints
func AssertDeleteSpendingOperationDeleteSpendingConstraints(obj DeleteSpendingOperationDeleteSpending) error {
	return nil
}
