// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type LoginRequest struct {
	Credentials Credentials `json:"credentials"`
}

// AssertLoginRequestRequired checks if the required fields are not zero-ed
func AssertLoginRequestRequired(obj LoginRequest) error {
	elements := map[string]interface{}{
		"credentials": obj.Credentials,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCredentialsRequired(obj.Credentials); err != nil {
		return err
	}
	return nil
}

// AssertLoginRequestConstraints checks if the values respects the defined constraints
func AssertLoginRequestConstraints(obj LoginRequest) error {
	if err := AssertCredentialsConstraints(obj.Credentials); err != nil {
		return err
	}
	return nil
}
