// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type UploadImageOperationUploadImage struct {

	// image identifier
	ImageId string `json:"imageId"`

	// base64 string representation of the image.
	Base64 string `json:"base64"`
}

// AssertUploadImageOperationUploadImageRequired checks if the required fields are not zero-ed
func AssertUploadImageOperationUploadImageRequired(obj UploadImageOperationUploadImage) error {
	elements := map[string]interface{}{
		"imageId": obj.ImageId,
		"base64":  obj.Base64,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUploadImageOperationUploadImageConstraints checks if the values respects the defined constraints
func AssertUploadImageOperationUploadImageConstraints(obj UploadImageOperationUploadImage) error {
	return nil
}
