// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// UpdateEmailOperation - Update email operation
type UpdateEmailOperation struct {
	UpdateEmail UpdateEmailRequest `json:"updateEmail"`
}

// AssertUpdateEmailOperationRequired checks if the required fields are not zero-ed
func AssertUpdateEmailOperationRequired(obj UpdateEmailOperation) error {
	elements := map[string]interface{}{
		"updateEmail": obj.UpdateEmail,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUpdateEmailRequestRequired(obj.UpdateEmail); err != nil {
		return err
	}
	return nil
}

// AssertUpdateEmailOperationConstraints checks if the values respects the defined constraints
func AssertUpdateEmailOperationConstraints(obj UpdateEmailOperation) error {
	if err := AssertUpdateEmailRequestConstraints(obj.UpdateEmail); err != nil {
		return err
	}
	return nil
}
