// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




// BaseOperation - Common properties for any operation
type BaseOperation struct {

	OperationId string `json:"operationId"`

	CreatedAt int64 `json:"createdAt"`

	AuthorId string `json:"authorId"`
}

// AssertBaseOperationRequired checks if the required fields are not zero-ed
func AssertBaseOperationRequired(obj BaseOperation) error {
	elements := map[string]interface{}{
		"operationId": obj.OperationId,
		"createdAt": obj.CreatedAt,
		"authorId": obj.AuthorId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBaseOperationConstraints checks if the values respects the defined constraints
func AssertBaseOperationConstraints(obj BaseOperation) error {
	return nil
}
