// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// AddSpendingRequest - Signup Request
type AddSpendingRequest struct {
	GroupId string `json:"groupId"`

	Payload SpendingPayload `json:"payload"`
}

// AssertAddSpendingRequestRequired checks if the required fields are not zero-ed
func AssertAddSpendingRequestRequired(obj AddSpendingRequest) error {
	elements := map[string]interface{}{
		"groupId": obj.GroupId,
		"payload": obj.Payload,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSpendingPayloadRequired(obj.Payload); err != nil {
		return err
	}
	return nil
}

// AssertAddSpendingRequestConstraints checks if the values respects the defined constraints
func AssertAddSpendingRequestConstraints(obj AddSpendingRequest) error {
	if err := AssertSpendingPayloadConstraints(obj.Payload); err != nil {
		return err
	}
	return nil
}
