// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

type SpendingsGroup struct {

	// Spending group's identifier.
	Id string `json:"id"`

	// Spending group's display name.
	Name *string `json:"name,omitempty"`

	// Spending's group creation unix timestamp.
	CreatedAt int32 `json:"createdAt"`

	Participants []SpendingsGroupParticipant `json:"participants"`

	Spendings []Spending `json:"spendings"`
}

// AssertSpendingsGroupRequired checks if the required fields are not zero-ed
func AssertSpendingsGroupRequired(obj SpendingsGroup) error {
	elements := map[string]interface{}{
		"id":           obj.Id,
		"createdAt":    obj.CreatedAt,
		"participants": obj.Participants,
		"spendings":    obj.Spendings,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Participants {
		if err := AssertSpendingsGroupParticipantRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Spendings {
		if err := AssertSpendingRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSpendingsGroupConstraints checks if the values respects the defined constraints
func AssertSpendingsGroupConstraints(obj SpendingsGroup) error {
	for _, el := range obj.Participants {
		if err := AssertSpendingsGroupParticipantConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Spendings {
		if err := AssertSpendingConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
