// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Verni
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi

// CreateSpendingGroupPushPayloadCsg - Create spending group push payload
type CreateSpendingGroupPushPayloadCsg struct {

	// Group identifier
	Gid string `json:"gid"`

	// Group name
	Gn *string `json:"gn,omitempty"`

	// Participant display names
	Pdns []string `json:"pdns"`
}

// AssertCreateSpendingGroupPushPayloadCsgRequired checks if the required fields are not zero-ed
func AssertCreateSpendingGroupPushPayloadCsgRequired(obj CreateSpendingGroupPushPayloadCsg) error {
	elements := map[string]interface{}{
		"gid":  obj.Gid,
		"pdns": obj.Pdns,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateSpendingGroupPushPayloadCsgConstraints checks if the values respects the defined constraints
func AssertCreateSpendingGroupPushPayloadCsgConstraints(obj CreateSpendingGroupPushPayloadCsg) error {
	return nil
}
