name: Xcode - Build and Analyze

on:
  push:
    branches: [main]
    paths:
      - "iosclient/**"
  pull_request:
    branches: [main]
    paths:
      - "iosclient/**"

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode_16.0.app"
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Build
        working-directory: ./iosclient
        shell: bash
        run: |
          cd Scripts
          chmod +x ./build.sh
          ./build.sh
