name: Xcode - Build and Analyze

on:
  push:
    branches: [main]
    paths:
      - "iosclient/**"
  pull_request:
    branches: [main]
    paths:
      - "iosclient/**"

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode_16.0.app"
      - name: Build
        run: |
          cd $(git rev-parse --show-toplevel)
          cd iosclient
          xcodebuild clean build analyze -project Verni.xcodeproj -scheme Verni -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro' | xcpretty && exit ${PIPESTATUS[0]}
