# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Build
      run: cd $(git rev-parse --show-toplevel) && cd ./server && go build -v cmd/accounty/main.go

    - name: TestJwt
      run: cd $(git rev-parse --show-toplevel) && cd ./server/internal/auth/jwt && go test -v . 

    - name: TestDB
      env:
        YDB_ADMIN_KEYS_JSON: ${{ secrets.YDB_ADMIN_KEYS_JSON }}
        YDB_TEST_ENDPOINT: ${{ secrets.YDB_TEST_ENDPOINT }}
      run: cd $(git rev-parse --show-toplevel) && cd ./server/internal/storage && sh storage_test.sh
