name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode_15.4.app"
      - name: Build
        run: |
          cd $(git rev-parse --show-toplevel) && cd ./client/iOS
          xcodebuild clean build analyze -project Accounty.xcodeproj -scheme Accounty -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro' | xcpretty && exit ${PIPESTATUS[0]}
