name: Xcode - Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode_16.0.app"
      - name: Test
        run: |
          cd $(git rev-parse --show-toplevel)
          xcodebuild test -project Accounty.xcodeproj -scheme Accounty -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro' | xcpretty && exit ${PIPESTATUS[0]}