name: Xcode - Test

on:
  push:
    branches: [main]
    paths:
      - 'iosclient/**'
  pull_request:
    branches: [main]
    paths:
      - 'iosclient/**'

jobs:
  build:
    name: Test default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode_16.0.app"
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Test
        shell: bash
        working-directory: ./iosclient
        run: sh ./Scripts/test.sh
        env:
          JSONBINS_KEY: ${{ secrets.JSONBINS_KEY }}