name: Xcode - Test

on:
  push:
    branches: [main]
    paths:
      - 'iosclient/**'
      - '.github/workflows/test_ios.yml'
  pull_request:
    branches: [main]
    paths:
      - 'iosclient/**'
      - '.github/workflows/test_ios.yml'

jobs:
  build:
    name: Test default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode.app"
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Test
        shell: bash
        working-directory: ./iosclient
        run: |
          cd Scripts
          chmod +x ./test.sh
          chmod +x ./coverage_report.sh
          ./test.sh
        env:
          JSONBINS_KEY: ${{ secrets.JSONBINS_KEY }}