name: Xcode - Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode_16.0.app"
      - name: Test
        run: |
          set -e -x
          cd $(git rev-parse --show-toplevel)
          xcodebuild test -project Verni.xcodeproj \
            -derivedDataPath testsDerivedData \
            -scheme Verni \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' | xcpretty
          report=$(find testsDerivedData -name "*.xcresult" -print | head -n 1)
          coverage=$(xcrun xccov view --report --json "${report}" | jq .lineCoverage)
          percentage=$(expr $coverage*100 | bc)
          percentage_int=${percentage%.*}
          curl --location --request PUT 'https://api.jsonbin.io/v3/b/66e66909acd3cb34a884adb5' \
            --header "X-Master-Key: ${JSONBINS_KEY}" \
            --header "Content-Type: application/json" \
            --data "{\"coverage\":\"${percentage_int}%\"}"
        env:
          JSONBINS_KEY: ${{ secrets.JSONBINS_KEY }}