name: Run Go unit tests

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/test_server.yml"
  pull_request:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/test_server.yml"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: verni_pwd
          POSTGRES_DB: verni_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        working-directory: ./server
        shell: bash
        run: |
          cd scripts
          chmod +x ./test.sh
          ./test.sh
